[package]
name = "roest"
version = "0.1.0"
authors = ["Felix Brakel <felixbrakel@quicknet.nl>"]

[dependencies]
sdl2 = "0.32.1"
gl = { path = "lib/gl" }
tobj = "0.1.6"

[features]
gl_debug = ["gl/debug"]