[package]
name = "roest_runtime"
version = "0.1.0"
authors = ["Felix Brakel <felixbrakel@quicknet.nl>"]
edition = "2018"
publish = false

#[workspace]

[dependencies]
gl = { path = "../lib/gl" }
gl_renderer = { path = "../lib/gl_renderer" }
renderer_derive = { path = "../lib/renderer_derive" }
roefs = { path = "../lib/roefs" }
sdl2 = "0.32.2"
lazy_static = "1.4.0"
failure = "0.1.7"
nalgebra = "0.20.0"


[build-dependencies]
walkdir = "2.2.9"

[features]
gl_debug = ["gl/debug"]